### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "NEW NAME 22",
  "price": "bob",
  "image_url": "test image url",
  "description": "test test test"
}
### CARTED_PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 3,
  "status": "carted",
  "order_id": 10
}

### PRODUCTS SHOW
GET http://localhost:3000/products/2.json

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "price": 100
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/3.json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Tom",
  "email": "tom@example.com",
  "password": "tomspassword",
  "password_confirmation": "tomspassword"
}  

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "tom@example.com",
  "password": "tomspassword"
}

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

{
  "name": "Tom",
  "width": 640,
  "height": 480
}

### ORDERS CREATE
POST http://localhost:3000/orders.json

### ORDERS SHOW
GET http://localhost:3000/orders/2.json